const { AttachmentBuilder } = require('discord.js');

function escapeHtml(value = '') {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function messageToHtml(message) {
  const author = escapeHtml(message.author?.tag || message.author?.username || 'Unknown User');
  const avatar = message.author?.displayAvatarURL?.({ extension: 'png', size: 64 }) || '';
  const content = escapeHtml(message.content || '').replace(/\n/g, '<br>');
  const attachments = [...message.attachments.values()].map(a => `<div class="attachment"><a href="${escapeHtml(a.url)}" target="_blank" rel="noopener noreferrer">📎 ${escapeHtml(a.name || 'Attachment')}</a></div>`).join('');
  const embeds = message.embeds.length ? `<div class="attachment">${message.embeds.length} embed(s)</div>` : '';
  return `<article class="message"><img class="avatar" src="${escapeHtml(avatar)}" alt=""><div class="body"><div class="meta"><strong>${author}</strong><time>${escapeHtml(message.createdAt.toLocaleString())}</time></div><div class="content">${content || '<span class="empty">[no text content]</span>'}</div>${attachments}${embeds}</div></article>`;
}

async function generateTranscript(channel, reason = null) {
  let messages = [];
  let before;
  while (messages.length < 100) {
    const batch = await channel.messages.fetch({ limit: Math.min(100, 100 - messages.length), before });
    if (!batch.size) break;
    messages.push(...batch.values());
    before = batch.last().id;
    if (batch.size < 100) break;
  }
  messages.sort((a, b) => a.createdTimestamp - b.createdTimestamp);

  const reasonBlock = reason ? `<div class="reason"><strong>Close reason:</strong> ${escapeHtml(reason)}</div>` : '';
  const body = messages.map(messageToHtml).join('');
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Transcript - ${escapeHtml(channel.name)}</title><style>
  :root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0a0a0a;color:#e7e7e7;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:1000px;margin:0 auto;padding:28px}.header{background:#0f0f0f;border:1px solid #262626;border-left:4px solid #0f0f0f;border-radius:14px;padding:22px;margin-bottom:18px;box-shadow:0 8px 28px #0008}.header h1{margin:0 0 8px;font-size:22px}.header p{margin:4px 0;color:#9b9b9b}.reason{margin-top:14px;padding:12px;border-radius:10px;background:#151515;border:1px solid #2b2b2b}.message{display:flex;gap:12px;padding:14px 10px;border-bottom:1px solid #1f1f1f}.avatar{width:38px;height:38px;border-radius:50%;background:#191919}.body{min-width:0;flex:1}.meta{display:flex;gap:10px;align-items:baseline}.meta strong{color:#fff}.meta time{font-size:12px;color:#777}.content{margin-top:4px;white-space:normal;overflow-wrap:anywhere}.empty{color:#666}.attachment{margin-top:7px}.attachment a{color:#bdbdbd}.footer{color:#666;font-size:12px;margin-top:20px}</style></head><body><main class="wrap"><section class="header"><h1>Grey Ticket Transcript</h1><p><strong>Channel:</strong> ${escapeHtml(channel.name)}</p><p><strong>Messages:</strong> ${messages.length} (maximum 100)</p>${reasonBlock}</section><section>${body}</section><div class="footer">Generated by Grey • Onyx transcript theme</div></main></body></html>`;
  return { attachment: new AttachmentBuilder(Buffer.from(html, 'utf8'), { name: `transcript-${channel.name}.html` }), html, count: messages.length };
}

module.exports = { generateTranscript };
